import { getServerSession } from 'next-auth/next';
import authOptions from './api/auth/[...nextauth]/authOptions';
import NavBar from './components/NavBar';
import './globals.css';
import Hydrate from './components/Hydrate';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="mx-64">
        <Hydrate>
          <NavBar user={session?.user} expires={session?.expires as string} />
          {children}
        </Hydrate>
      </body>
    </html>
  );
}
